from typing import Annotated, TypedDict, List, Dict, Any, Optional
from langgraph.graph.message import add_messages

class TravelState(TypedDict):
    # Input provided by user
    destination: str
    days: int
    budget: float
    travelers: Optional[int]
    interests: List[str]
    
    # Data gathered by Research Agent
    weather_info: Optional[Dict[str, Any]]
    nearby_attractions: List[Dict[str, Any]]
    malls: List[Dict[str, Any]]
    restaurants: List[Dict[str, Any]]
    movie_theatres: List[Dict[str, Any]]
    local_events: List[Dict[str, Any]]
    movie_recommendations: List[Dict[str, Any]]

    
    # Generated by Planner Agent
    itinerary: Optional[Dict[str, Any]]
    budget_breakdown: Optional[Dict[str, Any]]
    packing_checklist: List[str]
    alternate_activities: List[str]
    
    # Evaluated by Evaluator Agent
    safety_score: float
    travel_quality_score: float
    evaluator_feedback: Optional[str]
    
    # System Internal
    messages: Annotated[List[Any], add_messages]
    errors: List[str]
    loop_count: int

